# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.
main:  
  - name: About
    url: about/
    weight: 10

  - name: Interest
    url: interest/
    weight: 40
  
  - name: Project
    url: project/
    weight: 70

  - name: Seminar
    url: seminar/
    weight: 100
  - parent: Seminar
    name: 23-years
    url: /seminar/23
    weight: 110
  - parent: Seminar
    name: 24-years
    url: /seminar/24
    weight: 120
  - name: Award
    url: award/
    weight: 130
  - parent: Award
    name: Security Contest
    url: /award/security
    weight: 140
  - parent: Award
    name: etc
    url: /award/etc
    weight: 150